# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-08 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 8, 10, 31, 53, 180962, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
